In [2]:
# ライブラリ

In [3]:
import os
import sys
import glob
from IPython.display import display
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
#import japanize_matplotlib
import seaborn as sns 
import sweetviz as sv
import yaml

sys.path.append(os.path.abspath('..'))
from configs.config import *

In [4]:
import importlib
import configs.config
importlib.reload(configs.config)
from configs.config import *

In [5]:
pd.set_option("display.max_columns",100)
pd.set_option("display.max_rows", 500)

# データ読み込み

In [6]:
df_train = pd.read_csv(os.path.join(DIR_INPUT, FILE_NAME_TRAIN))
df_test = pd.read_csv(os.path.join(DIR_INPUT, FILE_NAME_TEST))
df_sample_submission = pd.read_csv(os.path.join(DIR_INPUT, FILE_SAMPLE_SUBMISSION))
df_udemy_activity = pd.read_csv(os.path.join(DIR_INPUT, FILE_NAME_UDEMY_ACTIVITY))
df_career = pd.read_csv(os.path.join(DIR_INPUT, FILE_NAME_CAREER))
df_dx = pd.read_csv(os.path.join(DIR_INPUT, FILE_NAME_DX))
df_hr = pd.read_csv(os.path.join(DIR_INPUT, FILE_NAME_HR))
df_overtime_work_by_month = pd.read_csv(os.path.join(DIR_INPUT, FILE_NAME_ORVER_TIME))
df_position_history = pd.read_csv(os.path.join(DIR_INPUT, FILE_NAME_POSITION_HISTORY))

In [7]:
print(f"train shape: {df_train.shape}")
print(f"test shape: {df_test.shape}")  
print(f"sample submission shape: {df_sample_submission.shape}")
print(f"udemy activity shape: {df_udemy_activity.shape}")
print(f"career shape: {df_career.shape}")
print(f"dx shape: {df_dx.shape}")
print(f"hr shape: {df_hr.shape}")
print(f"overtime work by month shape: {df_overtime_work_by_month.shape}")
print(f"position history shape: {df_position_history.shape}")

train shape: (7338, 3)
test shape: (11022, 2)
sample submission shape: (11022, 1)
udemy activity shape: (539164, 12)
career shape: (375, 46)
dx shape: (7100, 4)
hr shape: (7076, 4)
overtime work by month shape: (101439, 3)
position history shape: (8596, 4)

# 型、項目数、欠損値率

In [8]:
def calc_describe(df):
    dtypes = []
    val_counts_station = []
    isnull_station = []
    isnull_station_ratio = 100 * df.isnull().sum() / len(df)
    for col in df.columns:
        dtypes.append(str(df[col].dtype))
        val_counts_station.append(len(df[col].value_counts()))
        isnull_station.append(isnull_station_ratio[col])
    inds = ["型", "val_counts", "NaN率"]
    df_eda = pd.DataFrame([dtypes, val_counts_station, isnull_station], columns=df.columns, index=inds).T
    # df_eda.query("val_counts > 1")
    return df_eda

In [9]:
# 各データフレームのEDAを実行
for df, name in zip([df_train, df_test, df_sample_submission, df_udemy_activity, df_career, df_dx, df_hr, df_overtime_work_by_month, df_position_history],
             ["df_train", "df_test", "df_sample_submission", "df_udemy_activity", "df_career", "df_dx", "df_hr", "df_overtime_work_by_month", "df_position_history"]):
    print(f"{name}")
    df_eda = calc_describe(df)
    display(df_eda)

df_train

               型 val_counts NaN率
社員番号      object       1223  0.0
category  object          6  0.0
target     int64          2  0.0

df_test

               型 val_counts NaN率
社員番号      object       1837  0.0
category  object          6  0.0

df_sample_submission

              型 val_counts NaN率
target  float64      11022  0.0

df_udemy_activity

                    型 val_counts       NaN率
社員番号           object       2232        0.0
コースID           int64       3735        0.0
コースタイトル        object       3437        0.0
レクチャーもしくはクイズ   object          3        0.0
レクチャー/クイズID     int64     103384        0.0
レクチャー/クイズの題名   object      85023        0.0
開始日            object     392398        0.0
終了日            object     361588   8.569563
推定完了率%        float64       6410   0.629679
最終結果（クイズの場合）  float64        479  96.477139
マーク済み修了          bool          2        0.0
コースカテゴリー       object        305   0.000927

df_career

                                                         型 val_counts NaN率
社員番号                                                object        375  0.0
自分の能力を発揮できる仕事上の得意分野が見つかっている\n                       object          5  0.0
自分はどんな仕事をやりたいのか明らかである      \n                       object          5  0.0
自分は何を望んで今の仕事をしているのかわかっている\n                         object          5  0.0
自分なりの職業的な生き方に関する目標・目的がはっきりしている\n                    object          5  0.0
自分のこれからのキャリアには、あまり関心がない\n                           object          5  0.0
これからのキャリアを、より充実したものにしたいと強く思う\n                      object          5  0.0
キャリア設計（職業生活の設計）は、自分にとって重要な課題である\n                   object          5  0.0
これからのキャリアをどう歩むべきか、あまり考えていない\n                       object          5  0.0
納得いくキャリアを歩めるかどうかは、自分の責任だと思う\n                       object          5  0.0
キャリア形成は、自分自身の責任である\n                                object          5  0.0
納得いくキャリアを歩めない原因の大半は周囲の環境にある\n                       object          5  0.0
キャリアは周りの環境によって決められていくものだと思う\n                       object          5  0.0
新しい環境や状況にも、わりあい早くなじんで対応している                         object          5  0.0
職場環境の変化に対して自分なりに考えて対応している                           object          5  0.0
新しい職場に移ってもすぐに自分らしさを発揮している                           object          5  0.0
職場の制度や仕事が変わってもすぐ対応している                              object          5  0.0
自分の職種・業界分野における最新動向を常に情報収集している                       object          5  0.0
仕事のために新しいことをいろいろ勉強している                              object          5  0.0
社会・経済の動きや成り行きに関する情報を、積極的に収集している                     object          5  0.0
新しい知識・技術を積極的に学ぶように努めている                             object          5  0.0
新しい人間関係が構築できるように、社内外の活動に積極的に参加している                  object          5  0.0
仕事と直接関係ない人とも積極的に交流するようにしている                         object          5  0.0
新しいネットワークづくりに常に取り組んでいる                              object          5  0.0
自分の満足感を高めるように、仕事のやり方を工夫している                         object          5  0.0
常に自発的に仕事を行っている                                      object          5  0.0
自分の価値観やポリシーを持って仕事に取り組んでいる                           object          5  0.0
仕事の進め方や企画を立てる上で、今までの延長上のやり方ではなく、自分なりの発想を持って取り組んでいる  object          5  0.0
少人数チームで協力してタスクを完遂できる                                object          5  0.0
メンバー全員のアイデアを取り入れて成果物を作れる                            object          5  0.0
同僚や上司に向けて口頭でプレゼンテーションができる                           object          5  0.0
スライドや動画などのデジタル資料を用いて情報を共有できる                        object          5  0.0
異なる視点を比較して最適な解決策を選べる                                object          5  0.0
正解が一つでない問題に対して解決策を導き出せる                             object          5  0.0
複数のアイデアを試行し改善を重ねられる                                 object          5  0.0
困難な業務課題に対して独自の解決策を考案できる                             object          5  0.0
自分の進捗をモニタリングし計画を柔軟に調整できる                            object          5  0.0
フィードバックを受けて自ら仕事を改善できる                               object          5  0.0
業務データを可視化し BI ダッシュボードで意思決定に活用できる                    object          5  0.0
RPA／ノーコードツールで反復的な業務フローを自動化できる                       object          5  0.0
生成 AI や機械学習モデルを業務改善に活用できる                           object          5  0.0
クラウド環境のアクセス権限を監査し情報保護を徹底できる                         object          5  0.0
デジタルマーケティング施策（SNS 広告等）をデータで最適化できる                   object          5  0.0
顧客・市場データを用いて新商品・サービス企画を立案できる                        object          5  0.0
クラウド／DevOps 環境を構築し IaC で継続的デプロイを管理できる               object          5  0.0
デジタルツインや IoT データを用いたサプライチェーン最適化を提案・実装できる            object          5  0.0

df_dx

             型 val_counts NaN率
社員番号    object       1468  0.0
研修実施日   object         86  0.0
研修カテゴリ  object         10  0.0
研修名     object        100  0.0

df_hr

           型 val_counts       NaN率
社員番号  object       1550        0.0
カテゴリ  object         12        0.0
研修名   object         19  16.308649
実施日   object        767        0.0

df_overtime_work_by_month

             型 val_counts NaN率
社員番号    object       3060  0.0
date    object         36  0.0
hours  float64        175  0.0

df_position_history

           型 val_counts NaN率
社員番号  object       3060  0.0
year   int64          3  0.0
勤務区分  object          2  0.0
役職    object         10  0.0

# 基本統計量

In [10]:
for df, name in zip([df_train, df_test, df_sample_submission, df_udemy_activity, df_career, df_dx, df_hr, df_overtime_work_by_month, df_position_history],
             ["df_train", "df_test", "df_sample_submission", "df_udemy_activity", "df_career", "df_dx", "df_hr", "df_overtime_work_by_month", "df_position_history"]):
    print(f"{name}")
    display(df.head())

df_train

                       社員番号               category  target
0  -2Sq3E0WkZj8pL7jxdL3Cg==        コンテンツ・サービス・デザイン       0
1  -2Sq3E0WkZj8pL7jxdL3Cg==  コーポレート管理部門/技術・データ・BPR       0
2  -2Sq3E0WkZj8pL7jxdL3Cg==            プロダクトマネジメント       0
3  -2Sq3E0WkZj8pL7jxdL3Cg==                マーケティング       0
4  -2Sq3E0WkZj8pL7jxdL3Cg==             事業企画・開発・研究       0

df_test

                       社員番号               category
0  -1sqs0GXzpPJuAVKHUUFgg==        コンテンツ・サービス・デザイン
1  -1sqs0GXzpPJuAVKHUUFgg==  コーポレート管理部門/技術・データ・BPR
2  -1sqs0GXzpPJuAVKHUUFgg==            プロダクトマネジメント
3  -1sqs0GXzpPJuAVKHUUFgg==                マーケティング
4  -1sqs0GXzpPJuAVKHUUFgg==             事業企画・開発・研究

df_sample_submission

     target
0  0.559836
1  0.064199
2  0.026592
3  0.576083
4  0.542395

df_udemy_activity

,社員番号,コースID,コースタイトル,レクチャーもしくはクイズ,レクチャー/クイズID,レクチャー/クイズの題名,開始日,終了日,推定完了率%,最終結果（クイズの場合）,マーク済み修了,コースカテゴリー
0,-1sqs0GXzpPJuAVKHUUFgg==,4615016,企業オリジナル講座,Quiz,5528090,企業オリジナル講座,2022/4/11 10:10,2022/4/11 10:10,100.0,0.0,True,企業オリジナル講座
1,-1sqs0GXzpPJuAVKHUUFgg==,4615016,企業オリジナル講座,Quiz,5528090,企業オリジナル講座,2022/4/11 10:11,2022/4/11 10:11,100.0,100.0,True,企業オリジナル講座
2,-1sqs0GXzpPJuAVKHUUFgg==,4615016,企業オリジナル講座,Quiz,5528100,企業オリジナル講座,2022/4/11 10:26,2022/4/11 10:26,100.0,0.0,True,企業オリジナル講座
3,-1sqs0GXzpPJuAVKHUUFgg==,4615016,企業オリジナル講座,Quiz,5528100,企業オリジナル講座,2022/4/11 10:27,2022/4/11 10:27,100.0,100.0,True,企業オリジナル講座
4,-1sqs0GXzpPJuAVKHUUFgg==,4615016,企業オリジナル講座,Quiz,5528102,企業オリジナル講座,2022/4/11 10:21,2022/4/11 10:21,100.0,100.0,True,企業オリジナル講座

df_career

,社員番号,自分の能力を発揮できる仕事上の得意分野が見つかっている\n,自分はどんな仕事をやりたいのか明らかである \n,自分は何を望んで今の仕事をしているのかわかっている\n,自分なりの職業的な生き方に関する目標・目的がはっきりしている\n,自分のこれからのキャリアには、あまり関心がない\n,これからのキャリアを、より充実したものにしたいと強く思う\n,キャリア設計（職業生活の設計）は、自分にとって重要な課題である\n,これからのキャリアをどう歩むべきか、あまり考えていない\n,納得いくキャリアを歩めるかどうかは、自分の責任だと思う\n,キャリア形成は、自分自身の責任である\n,納得いくキャリアを歩めない原因の大半は周囲の環境にある\n,キャリアは周りの環境によって決められていくものだと思う\n,新しい環境や状況にも、わりあい早くなじんで対応している,職場環境の変化に対して自分なりに考えて対応している,新しい職場に移ってもすぐに自分らしさを発揮している,職場の制度や仕事が変わってもすぐ対応している,自分の職種・業界分野における最新動向を常に情報収集している,仕事のために新しいことをいろいろ勉強している,社会・経済の動きや成り行きに関する情報を、積極的に収集している,新しい知識・技術を積極的に学ぶように努めている,新しい人間関係が構築できるように、社内外の活動に積極的に参加している,仕事と直接関係ない人とも積極的に交流するようにしている,新しいネットワークづくりに常に取り組んでいる,自分の満足感を高めるように、仕事のやり方を工夫している,常に自発的に仕事を行っている,自分の価値観やポリシーを持って仕事に取り組んでいる,仕事の進め方や企画を立てる上で、今までの延長上のやり方ではなく、自分なりの発想を持って取り組んでいる,少人数チームで協力してタスクを完遂できる,メンバー全員のアイデアを取り入れて成果物を作れる,同僚や上司に向けて口頭でプレゼンテーションができる,スライドや動画などのデジタル資料を用いて情報を共有できる,異なる視点を比較して最適な解決策を選べる,正解が一つでない問題に対して解決策を導き出せる,複数のアイデアを試行し改善を重ねられる,困難な業務課題に対して独自の解決策を考案できる,自分の進捗をモニタリングし計画を柔軟に調整できる,フィードバックを受けて自ら仕事を改善できる,業務データを可視化し BI ダッシュボードで意思決定に活用できる,RPA／ノーコードツールで反復的な業務フローを自動化できる,生成 AI や機械学習モデルを業務改善に活用できる,クラウド環境のアクセス権限を監査し情報保護を徹底できる,デジタルマーケティング施策（SNS 広告等）をデータで最適化できる,顧客・市場データを用いて新商品・サービス企画を立案できる,クラウド／DevOps 環境を構築し IaC で継続的デプロイを管理できる,デジタルツインや IoT データを用いたサプライチェーン最適化を提案・実装できる
0,-4taxxVbT1nU-J5fHWmDfQ==,4 そう思う／当てはまる,3 どちらとも言えない,4 そう思う／当てはまる,3 どちらとも言えない,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,3 どちらとも言えない,4 そう思う／当てはまる,3 どちらとも言えない,3 どちらとも言えない,5 強くそう思う／とても当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,3 どちらとも言えない,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,4 そう思う／当てはまる,3 どちらとも言えない,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,4 そう思う／当てはまる,3 どちらとも言えない,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,5 強くそう思う／とても当てはまる,3 どちらとも言えない,2 あまりそう思わない／あまり当てはまらない,3 どちらとも言えない,3 どちらとも言えない,2 あまりそう思わない／あまり当てはまらない,2 あまりそう思わない／あまり当てはまらない,2 あまりそう思わない／あまり当てはまらない,2 あまりそう思わない／あまり当てはまらない
1,-EtuCRccKFQgi3UfXRvRkA==,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,1 全くそう思わない／全く当てはまらない,1 全くそう思わない／全く当てはまらない,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,1 全くそう思わない／全く当てはまらない,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,1 全くそう思わない／全く当てはまらない,1 全くそう思わない／全く当てはまらない,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,1 全くそう思わない／全く当てはまらない,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,1 全くそう思わない／全く当てはまらない
2,-JxDfe1I3lMhJDvo7mmvoA==,4 そう思う／当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,4 そう思う／当てはまる,1 全くそう思わない／全く当てはまらない,5 強くそう思う／とても当てはまる,4 そう思う／当てはまる,1 全くそう思わない／全く当てはまらない,4 そう思う／当てはまる,4 そう思う／当てはまる,1 全くそう思わない／全く当てはまらない,1 全くそう思わない／全く当てはまらない,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,2 あまりそう思わない／あまり当てはまらない,2 あまりそう思わない／あまり当てはまらない,4 そう思う／当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,3 どちらとも言えない,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,5 強くそう思う／とても当てはまる,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,2 あまりそう思わない／あまり当てはまらない
3,-Q5JF_Zj03QFrpbCJWPR3A==,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,4 そう思う／当てはまる,1 全くそう思わない／全く当てはまらない,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,1 全くそう思わない／全く当てはまらない,1 全くそう思わない／全く当てはまらない,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,4 そう思う／当てはまる,5 強くそう思う／とても当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,5 強くそう思う／とても当てはまる,4 そう思う／当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,2 あまりそう思わない／あまり当てはまらない,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,2 あまりそう思わない／あまり当てはまらない,3 どちらとも言えない,5 強くそう思う／とても当てはまる,3 どちらとも言えない,2 あまりそう思わない／あまり当てはまらない
4,-WNGlH_XHI3_niAnslX8gg==,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,3 どちらとも言えない,3 どちらとも言えない,2 あまりそう思わない／あまり当てはまらない,4 そう思う／当てはまる,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,1 全くそう思わない／全く当てはまらない,2 あまりそう思わない／あまり当てはまらない,3 どちらとも言えない,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,3 どちらとも言えない,2 あまりそう思わない／あまり当てはまらない,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,2 あまりそう思わない／あまり当てはまらない,3 どちらとも言えない,2 あまりそう思わない／あまり当てはまらない,2 あまりそう思わない／あまり当てはまらない,4 そう思う／当てはまる,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない

df_dx

,社員番号,研修実施日,研修カテゴリ,研修名
0,-2Sq3E0WkZj8pL7jxdL3Cg==,2024-04-15 00:00:00,リテラシー_DX基礎,【DX基礎研修】DX概論
1,-2Sq3E0WkZj8pL7jxdL3Cg==,2024-04-16 00:00:00,リテラシー_DX基礎,【DX基礎研修】ものづくり概論
2,-5W_JQCSTAYe2gGJMuT4_w==,2023-04-20 00:00:00,リテラシー_DX基礎,【DX基礎研修】社内事例①
3,-5W_JQCSTAYe2gGJMuT4_w==,2023-04-20 00:00:00,リテラシー_DX基礎,【DX基礎研修】社内事例②
4,-5W_JQCSTAYe2gGJMuT4_w==,2024-04-15 00:00:00,リテラシー_DX基礎,【DX基礎研修】イントロダクション

df_hr

                       社員番号          カテゴリ       研修名                    実施日
0  -4taxxVbT1nU-J5fHWmDfQ==      3等級昇格者研修  3等級昇格者研修    2023-06-02 00:00:00
1  -4taxxVbT1nU-J5fHWmDfQ==  ビジネススキルアップ研修   マーケティング  2022/11/15,2022/11/29
2  -4taxxVbT1nU-J5fHWmDfQ==  ビジネススキルアップ研修   マーケティング  2022/11/15,2022/11/29
3  -4taxxVbT1nU-J5fHWmDfQ==  ビジネススキルアップ研修   マーケティング  2022/11/15,2022/11/29
4  -4taxxVbT1nU-J5fHWmDfQ==  ビジネススキルアップ研修   マーケティング  2022/11/15,2022/11/29

df_overtime_work_by_month

                       社員番号        date  hours
0  -1sqs0GXzpPJuAVKHUUFgg==  2022-01-01   10.0
1  -1sqs0GXzpPJuAVKHUUFgg==  2022-02-01   11.0
2  -1sqs0GXzpPJuAVKHUUFgg==  2022-03-01   18.0
3  -1sqs0GXzpPJuAVKHUUFgg==  2022-04-01   30.0
4  -1sqs0GXzpPJuAVKHUUFgg==  2022-05-01   27.0

df_position_history

                       社員番号  year 勤務区分        役職
0  -1sqs0GXzpPJuAVKHUUFgg==    22  正社員        一般
1  -1sqs0GXzpPJuAVKHUUFgg==    23  正社員        一般
2  -1sqs0GXzpPJuAVKHUUFgg==    24  正社員  グループリーダー
3  -2Sq3E0WkZj8pL7jxdL3Cg==    23  正社員        一般
4  -2Sq3E0WkZj8pL7jxdL3Cg==    24  正社員        一般

In [11]:
for df, name in zip([df_train, df_test, df_sample_submission, df_udemy_activity, df_career, df_dx, df_hr, df_overtime_work_by_month, df_position_history],
             ["df_train", "df_test", "df_sample_submission", "df_udemy_activity", "df_career", "df_dx", "df_hr", "df_overtime_work_by_month", "df_position_history"]):
    print(f"{name}")
    display(df.describe())

df_train

            target
count  7338.000000
mean      0.039384
std       0.194520
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000

df_test

                            社員番号         category
count                      11022            11022
unique                      1837                6
top     -1sqs0GXzpPJuAVKHUUFgg==  コンテンツ・サービス・デザイン
freq                           6             1837

df_sample_submission

             target
count  11022.000000
mean       0.501904
std        0.289213
min        0.000059
25%        0.252466
50%        0.504537
75%        0.752157
max        0.999937

df_udemy_activity

              コースID   レクチャー/クイズID         推定完了率%  最終結果（クイズの場合）
count  5.391640e+05  5.391640e+05  535769.000000  18994.000000
mean   3.790260e+06  2.688842e+07      95.135240     74.986088
std    1.400693e+06  1.114872e+07      18.938701     33.658643
min    1.530500e+04  4.882000e+03       0.000000      0.000000
25%    2.776760e+06  1.914245e+07     100.000000     56.557500
50%    4.030628e+06  2.783656e+07     100.000000    100.000000
75%    4.847846e+06  3.532076e+07     100.000000    100.000000
max    6.652121e+06  5.095909e+07     200.000000    133.330000

df_career

,社員番号,自分の能力を発揮できる仕事上の得意分野が見つかっている\n,自分はどんな仕事をやりたいのか明らかである \n,自分は何を望んで今の仕事をしているのかわかっている\n,自分なりの職業的な生き方に関する目標・目的がはっきりしている\n,自分のこれからのキャリアには、あまり関心がない\n,これからのキャリアを、より充実したものにしたいと強く思う\n,キャリア設計（職業生活の設計）は、自分にとって重要な課題である\n,これからのキャリアをどう歩むべきか、あまり考えていない\n,納得いくキャリアを歩めるかどうかは、自分の責任だと思う\n,キャリア形成は、自分自身の責任である\n,納得いくキャリアを歩めない原因の大半は周囲の環境にある\n,キャリアは周りの環境によって決められていくものだと思う\n,新しい環境や状況にも、わりあい早くなじんで対応している,職場環境の変化に対して自分なりに考えて対応している,新しい職場に移ってもすぐに自分らしさを発揮している,職場の制度や仕事が変わってもすぐ対応している,自分の職種・業界分野における最新動向を常に情報収集している,仕事のために新しいことをいろいろ勉強している,社会・経済の動きや成り行きに関する情報を、積極的に収集している,新しい知識・技術を積極的に学ぶように努めている,新しい人間関係が構築できるように、社内外の活動に積極的に参加している,仕事と直接関係ない人とも積極的に交流するようにしている,新しいネットワークづくりに常に取り組んでいる,自分の満足感を高めるように、仕事のやり方を工夫している,常に自発的に仕事を行っている,自分の価値観やポリシーを持って仕事に取り組んでいる,仕事の進め方や企画を立てる上で、今までの延長上のやり方ではなく、自分なりの発想を持って取り組んでいる,少人数チームで協力してタスクを完遂できる,メンバー全員のアイデアを取り入れて成果物を作れる,同僚や上司に向けて口頭でプレゼンテーションができる,スライドや動画などのデジタル資料を用いて情報を共有できる,異なる視点を比較して最適な解決策を選べる,正解が一つでない問題に対して解決策を導き出せる,複数のアイデアを試行し改善を重ねられる,困難な業務課題に対して独自の解決策を考案できる,自分の進捗をモニタリングし計画を柔軟に調整できる,フィードバックを受けて自ら仕事を改善できる,業務データを可視化し BI ダッシュボードで意思決定に活用できる,RPA／ノーコードツールで反復的な業務フローを自動化できる,生成 AI や機械学習モデルを業務改善に活用できる,クラウド環境のアクセス権限を監査し情報保護を徹底できる,デジタルマーケティング施策（SNS 広告等）をデータで最適化できる,顧客・市場データを用いて新商品・サービス企画を立案できる,クラウド／DevOps 環境を構築し IaC で継続的デプロイを管理できる,デジタルツインや IoT データを用いたサプライチェーン最適化を提案・実装できる
count,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375
unique,375,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
top,-4taxxVbT1nU-J5fHWmDfQ==,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,5 強くそう思う／とても当てはまる,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,4 そう思う／当てはまる,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,3 どちらとも言えない,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,4 そう思う／当てはまる,3 どちらとも言えない,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,2 あまりそう思わない／あまり当てはまらない,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,1 全くそう思わない／全く当てはまらない,4 そう思う／当てはまる,1 全くそう思わない／全く当てはまらない,1 全くそう思わない／全く当てはまらない
freq,1,233,212,222,188,150,174,181,153,186,196,172,155,220,277,185,245,160,195,170,204,120,125,128,245,215,249,237,274,235,242,249,264,242,267,226,233,281,120,112,162,102,128,115,182,183

df_dx

,社員番号,研修実施日,研修カテゴリ,研修名
count,7100,7100,7100,7100
unique,1468,86,10,100
top,pxJxAVJh9De4pduKjrPUlA==,2023-04-17 00:00:00,リテラシー_DX基礎,【DX基礎研修】DX概論
freq,34,1084,4252,453

df_hr

                            社員番号          カテゴリ       研修名                  実施日
count                       7076          7076      5922                 7076
unique                      1550            12        19                  767
top     M-J4K8nv5EWsiGlan6HRNA==  ビジネススキルアップ研修  アカウンティング  2024-12-01 00:00:00
freq                          34          2940       918                  316

df_overtime_work_by_month

               hours
count  101439.000000
mean       38.600883
std        22.332754
min         0.000000
25%        23.000000
50%        39.000000
75%        54.000000
max       195.000000

df_position_history

              year
count  8596.000000
mean     23.066892
std       0.800417
min      22.000000
25%      22.000000
50%      23.000000
75%      24.000000
max      24.000000

# train

In [32]:
df_train

                          社員番号               category  target
0     -2Sq3E0WkZj8pL7jxdL3Cg==        コンテンツ・サービス・デザイン       0
1     -2Sq3E0WkZj8pL7jxdL3Cg==  コーポレート管理部門/技術・データ・BPR       0
2     -2Sq3E0WkZj8pL7jxdL3Cg==            プロダクトマネジメント       0
3     -2Sq3E0WkZj8pL7jxdL3Cg==                マーケティング       0
4     -2Sq3E0WkZj8pL7jxdL3Cg==             事業企画・開発・研究       0
...                        ...                    ...     ...
7333  zuplFpzBoM4c1dFy5HPXqg==  コーポレート管理部門/技術・データ・BPR       0
7334  zuplFpzBoM4c1dFy5HPXqg==            プロダクトマネジメント       0
7335  zuplFpzBoM4c1dFy5HPXqg==                マーケティング       0
7336  zuplFpzBoM4c1dFy5HPXqg==             事業企画・開発・研究       0
7337  zuplFpzBoM4c1dFy5HPXqg==                     営業       0

[7338 rows x 3 columns]

In [35]:
df_train['category'].value_counts()

category
コンテンツ・サービス・デザイン          1223
コーポレート管理部門/技術・データ・BPR    1223
プロダクトマネジメント              1223
マーケティング                  1223
事業企画・開発・研究               1223
営業                       1223
Name: count, dtype: int64

In [14]:
df_train.groupby('category')['target'].value_counts().reset_index()

                 category  target  count
0         コンテンツ・サービス・デザイン       0   1193
1         コンテンツ・サービス・デザイン       1     30
2   コーポレート管理部門/技術・データ・BPR       0   1161
3   コーポレート管理部門/技術・データ・BPR       1     62
4             プロダクトマネジメント       0   1162
5             プロダクトマネジメント       1     61
6                 マーケティング       0   1171
7                 マーケティング       1     52
8              事業企画・開発・研究       0   1167
9              事業企画・開発・研究       1     56
10                     営業       0   1195
11                     営業       1     28

# df_test

In [15]:
df_test.head()

                       社員番号               category
0  -1sqs0GXzpPJuAVKHUUFgg==        コンテンツ・サービス・デザイン
1  -1sqs0GXzpPJuAVKHUUFgg==  コーポレート管理部門/技術・データ・BPR
2  -1sqs0GXzpPJuAVKHUUFgg==            プロダクトマネジメント
3  -1sqs0GXzpPJuAVKHUUFgg==                マーケティング
4  -1sqs0GXzpPJuAVKHUUFgg==             事業企画・開発・研究

In [34]:
df_test['category'].value_counts()

category
コンテンツ・サービス・デザイン          1837
コーポレート管理部門/技術・データ・BPR    1837
プロダクトマネジメント              1837
マーケティング                  1837
事業企画・開発・研究               1837
営業                       1837
Name: count, dtype: int64

# udemy_activity

In [16]:
df_udemy_activity

,社員番号,コースID,コースタイトル,レクチャーもしくはクイズ,レクチャー/クイズID,レクチャー/クイズの題名,開始日,終了日,推定完了率%,最終結果（クイズの場合）,マーク済み修了,コースカテゴリー
0,-1sqs0GXzpPJuAVKHUUFgg==,4615016,企業オリジナル講座,Quiz,5528090,企業オリジナル講座,2022/4/11 10:10,2022/4/11 10:10,100.0,0.0,True,企業オリジナル講座
1,-1sqs0GXzpPJuAVKHUUFgg==,4615016,企業オリジナル講座,Quiz,5528090,企業オリジナル講座,2022/4/11 10:11,2022/4/11 10:11,100.0,100.0,True,企業オリジナル講座
2,-1sqs0GXzpPJuAVKHUUFgg==,4615016,企業オリジナル講座,Quiz,5528100,企業オリジナル講座,2022/4/11 10:26,2022/4/11 10:26,100.0,0.0,True,企業オリジナル講座
3,-1sqs0GXzpPJuAVKHUUFgg==,4615016,企業オリジナル講座,Quiz,5528100,企業オリジナル講座,2022/4/11 10:27,2022/4/11 10:27,100.0,100.0,True,企業オリジナル講座
4,-1sqs0GXzpPJuAVKHUUFgg==,4615016,企業オリジナル講座,Quiz,5528102,企業オリジナル講座,2022/4/11 10:21,2022/4/11 10:21,100.0,100.0,True,企業オリジナル講座
...,...,...,...,...,...,...,...,...,...,...,...,...
539159,zxY0Eflwm1tYj1Wt6vo_1g==,5264112,企業オリジナル講座,Video_lecture,37311144,企業オリジナル講座,2023/6/14 9:56,2023/6/14 9:56,100.0,NaN,True,企業オリジナル講座
539160,zxY0Eflwm1tYj1Wt6vo_1g==,5264112,企業オリジナル講座,Video_lecture,37311150,企業オリジナル講座,2023/6/14 9:57,2023/6/14 9:57,100.0,NaN,True,企業オリジナル講座
539161,zxY0Eflwm1tYj1Wt6vo_1g==,6098315,企業オリジナル講座,Video_lecture,45012691,企業オリジナル講座,2024/9/27 15:39,2024/9/27 16:17,100.0,NaN,True,企業オリジナル講座
539162,zxY0Eflwm1tYj1Wt6vo_1g==,6106205,企業オリジナル講座,Video_lecture,45088199,企業オリジナル講座,2024/12/16 16:21,2024/12/16 17:39,100.0,NaN,True,企業オリジナル講座
539163,zxY0Eflwm1tYj1Wt6vo_1g==,6169093,企業オリジナル講座,Video_lecture,45683413,企業オリジナル講座,2024/9/27 16:21,2024/9/27 17:39,100.0,NaN,True,企業オリジナル講座

In [17]:
df_udemy_activity.dtypes

社員番号             object
コースID             int64
コースタイトル          object
レクチャーもしくはクイズ     object
レクチャー/クイズID       int64
レクチャー/クイズの題名     object
開始日              object
終了日              object
推定完了率%          float64
最終結果（クイズの場合）    float64
マーク済み修了            bool
コースカテゴリー         object
dtype: object

In [38]:
df_udemy_activity['コースタイトル'].value_counts().reset_index()

                                                コースタイトル  count
0                                             企業オリジナル講座  42743
1                       ITパスポート最速合格コース ～効率的な学習で0から合格まで～  11800
2     【ChatGPTで仕事を10倍効率化】AIを味方につけてデキる人材になる！ビジネスに使える1...   8516
3     【旧講座】今日から始めるデジタルトランスフォーメーション！テクノロジーの仕組みからデータ活用...   6556
4                   未経験者でもスッキリ分かる！初心者のためのプロダクトマネージャー超入門   5203
...                                                 ...    ...
3432  Master Discrete Mathematics: Sets, Math Logic,...      1
3433  ④社労士受験講座　NO4：雇用保険法「右脳を使って効率学習！イメージマスター社労士講座　20...      1
3434  ⑦社労士受験講座　NO７：国民年金法「右脳を使って効率学習！イメージマスター社労士講座　20...      1
3435  Certified Minitab Beginner: Graphical Tools (A...      1
3436  Ethereum : Decentralized Application Design & ...      1

[3437 rows x 2 columns]

In [40]:
df_udemy_activity['レクチャーもしくはクイズ'].value_counts().reset_index()

    レクチャーもしくはクイズ   count
0  Video_lecture  491743
1  Other_lecture   25032
2           Quiz   22389

In [41]:
df_udemy_activity['レクチャー/クイズの題名'].value_counts().reset_index()

              レクチャー/クイズの題名  count
0                企業オリジナル講座  42743
1             このセクションで学ぶこと   5585
2                     はじめに   5039
3              このセクションのまとめ   4030
4                      まとめ   2129
...                    ...    ...
85018             ITシステム構成      1
85019          Part.3-3 デモ      1
85020         セッションとCookie      1
85021               HTML概要      1
85022  Fix this app design      1

[85023 rows x 2 columns]

In [42]:
df_udemy_activity['コースカテゴリー'].value_counts().reset_index()

                                              コースカテゴリー  count
0                                               ビジネス戦略  46497
1                                            企業オリジナル講座  42743
2                                                 IT資格  39244
3                               オフィスの生産性向上とコラボレーションツール  38302
4                                           ビジネス向け生成AI  24513
5                                             プロジェクト管理  19770
6                                            マーケティング戦略  12883
7                                            チームマネジメント  12573
8                                            プログラミング言語  12021
9                                                ウェブ開発  11471
10                                              ファイナンス  11322
11                                         デジタルマーケティング   9550
12                                        コミュニケーションの基本   9263
13                                                統計分析   8534
14       オフィスの生産性向上とコラボレーションツール, 推奨講座, 業務効率化_エクセル_プレゼン   7148
15                                              プロマネ資格   6826
16                                         プロダクトマネジメント   6749
17                                                機械学習   6605
18                                           営業スキル・ツール   6479
19     PMI Professional Development Units（PDU）, プロマネ資格   6142
20                                       マーケティング分析と自動化   5849
21                                                英語学習   5789
22                                             OSとサーバー   5731
23                                              データ可視化   5704
24                                             アナリティクス   5581
25                                                人材開発   5120
26             オフィスの生産性向上とコラボレーションツール, 業務効率化_エクセル_プレゼン   4957
27                                              英語試験準備   4838
28                                      ソフトウェアエンジニアリング   4826
29                                        テクノロジー向け生成AI   4705
30                                     アナリティクス, ビジネス戦略   4587
31                                               個人の成長   4355
32                                              キャリア成功   4248
33                                              ネットワーク   4201
34                                             リーダーシップ   4153
35                                      UX（ユーザー体験）デザイン   3996
36                                               人事の基礎   3550
37                                                  会計   3390
38                           マーケティング戦略, 新規事業立案_マーケティング   3303
39                                             ペイドメディア   3023
40                                              クラウド資格   3023
41                                           会計, 財務_会計   3005
42                                    ソーシャルメディアマーケティング   2931
43                       UX（ユーザー体験）デザイン, ウェブとモバイルのデザイン   2923
44                      データサイエンス(data science), データ可視化   2881
45                                              モバイル開発   2872
46                                        コンテンツマーケティング   2775
47                                              ビッグデータ   2748
48                                              クラウド開発   2731
49                                           DBデザイン・開発   2359
50   おすすめ講座, オススメ講座, 推奨講座, 新規事業立案_マーケティング, スピーチとプレゼ...   2256
51                              ウェブ開発, 開発(development)   2255
52                                          アジャイル・スクラム   2250
53                                        サイバーセキュリティ意識   2224
54                                              DevOps   2189
55                                 チームマネジメント, プロジェクト管理   2140
56                                        サイバーセキュリティ認証   1967
57                     デザインとイラストレーションのツール, 写真と動画の編集ツール   1898
58                                         写真と動画の編集ツール   1895
59                                        データ可視化, 統計分析   1833
60                                  デザインとイラストレーションのツール   1828
61             IT×ビジネス, データサイエンス(data science), ビッグデータ   1610
62                                       ノーコード/ローコード開発   1598
63                     IT資格, スプレッドシート, 業務効率化_エクセル_プレゼン   1553
64                        IT×ビジネス, チームマネジメント, プロジェクト管理   1535
65                                               投資・株式   1491
66                                          ゲーム開発とデザイン   1403
67                                ウェブとモバイルのデザイン, ウェブ開発   1365
68                        コンテンツマーケティング, 新規事業立案_マーケティング   1303
69                     営業スキル・ツール, 推奨講座, 新規事業立案_マーケティング   1261
70              デジタルマーケティング, 検索エンジン最適化, 新規事業立案_マーケティング   1261
71                                    ビジネス向け生成AI, 英語学習   1236
72                                        文章のコミニュケーション   1180
73                                           ソフトウェアテスト   1173
74                                              芸術・創造性   1155
75                             DevOps, 開発(development)   1111
76                    オフィスの生産性向上とコラボレーションツール, スプレッドシート   1079
77                                    環境、社会、ガバナンス（ESG）   1043
78                        AI・機械学習, IT×ビジネス, TEST, 機械学習    942
79                            VCR専用（非公開）, コミュニケーションの基本    878
80                            ビジネス戦略, 環境、社会、ガバナンス（ESG）    831
81                                               世界の言語    802
82                                       ファイナンス, 財務_会計    799
83                IT×ビジネス, 新規事業立案_マーケティング, デジタルマーケティング    737
84        スピーチとプレゼンテーション, オススメ講座, 推奨講座, 新規事業立案_マーケティング    729
85                                           世界の言語, 会計    717
86                        おすすめ講座, 【社内限定公開】トレーニング, 人材開発    716
87                                 カスタマーサクセス&カスタマーサービス    693
88                      ウェブとモバイルのデザイン, ウェブ開発, デザイン_創造力    675
89                        データサイエンス(data science), 機械学習    663
90                    ソーシャルメディアマーケティング, 新規事業立案_マーケティング    654
91                                      3Dとアニメーションのツール    617
92                                               数学と統計    596
93   おすすめ講座, IT×ビジネス, オススメ講座, データサイエンス(data science...    592
94                                                運用管理    566
95                                      スピーチとプレゼンテーション    553
96             オススメ講座, 推奨講座, 新規事業立案_マーケティング, マーケティング戦略    543
97                                 IT×ビジネス, アジャイル・スクラム    542
98                          プログラミング言語, 開発(development)    537
99                                    ウェブ開発, プログラミング言語    501
100          コンテンツマーケティング, デジタルマーケティング, 新規事業立案_マーケティング    498
101          スプレッドシート, マーケティング戦略, 推奨講座, 新規事業立案_マーケティング    477
102                                   OS（オペレーティングシステム）    466
103                                 ガバナンス、リスク、コンプライアンス    455
104              ソフトウェアテスト, プログラミング言語, 開発(development)    437
105          デザイン_創造力, デザインとイラストレーションのツール, 写真と動画の編集ツール    430
106  おすすめ講座, オススメ講座, 推奨講座, 業務効率化_エクセル_プレゼン, スピーチとプレ...    400
107  PMI Professional Development Units（PDU）, プロジェクト管理    390
108                            クラウド開発, 開発(development)    390
109                             DevOps, ソフトウェアエンジニアリング    389
110  オフィスの生産性向上とコラボレーションツール, オススメ講座, 推奨講座, 業務効率化_エク...    378
111                                           データベース管理    372
112                                          検索エンジン最適化    369
113                                          健康・フィットネス    353
114                        ダイバーシティ、エクイティ、インクルージョン（DEI）    340
115                                             ビジネス分析    337
116                            3Dとアニメーションのツール, ゲームデザイン    332
117                                       ビッグデータ, 機械学習    330
118                 推奨講座, 新規事業立案_マーケティング, 文章のコミニュケーション    329
119                 UX（ユーザー体験）デザイン, デザインとイラストレーションのツール    328
120                                  プログラミング言語, モバイル開発    318
121                                           会計ソフトウェア    317
122                                      AI・機械学習, 機械学習    314
123                                      ウェブとモバイルのデザイン    308
124                 オフィスの生産性向上とコラボレーションツール, ワードプロセッシング    302
125                     ウェブ開発, オススメ講座, 開発(development)    302
126                                     ビジネス戦略, ビッグデータ    301
127                     スピーチとプレゼンテーション, 新規事業立案_マーケティング    288
128                               【社内限定公開】トレーニング, 人材開発    284
129                Offensive Security, 開発(development)    271
130                                       IT資格, クラウド資格    268
131                                            メールと生産性    262
132                                 Offensive Security    254
133                            IT×ビジネス, ソフトウェアエンジニアリング    248
134                                     クラウド基礎, クラウド開発    222
135                                ウェブ開発, テクノロジー向け生成AI    217
136                      マーケティング分析と自動化, 新規事業立案_マーケティング    212
137                               英語学習, 語学学習(language)    210
138                                             ハードウェア    208
139                          ファイナンス, 財務モデリング・分析, 財務_会計    202
140         おすすめ講座, 新規事業立案_マーケティング, チームマネジメント, リーダーシップ    194
141             おすすめ講座, IT×ビジネス, 業務効率化_エクセル_プレゼン, 人材開発    193
142                                             新規事業開発    183
143                      IT資格, クラウド開発, 開発(development)    177
144                                   プログラミング言語, 数学と統計    175
145                                     オススメ講座, ビジネス戦略    174
146                     AI・機械学習, IT×ビジネス, オススメ講座, 機械学習    174
147                                        テスト, ビジネス戦略    173
148                                  データ可視化, プログラミング言語    173
149                                           スプレッドシート    171
150  AI・機械学習, データサイエンス(data science), アナリティクス, ビッグデ...    162
151     PMI Professional Development Units（PDU）, 個人の成長    154
152                       デザイン_創造力, デザインとイラストレーションのツール    153
153                                             ライフスキル    153
154                       おすすめ講座, 語学学習(language), 英語学習    142
155                  チームマネジメント, ビジネス戦略, 新規事業立案_マーケティング    139
156                 チームマネジメント, リーダーシップ, 新規事業立案_マーケティング    138
157                            モバイル開発, 開発(development)    125
158                                         ファイナンス, 会計    120
159                          データベース管理, 開発(development)    117
160                       文章のコミニュケーション, 語学学習(language)    117
161                     DevOps, ウェブ開発, 開発(development)    111
162                        ゲーム開発とデザイン, 開発(development)    111
163                                      ウェブ開発, ビジネス戦略    109
164                           OSとサーバー, 開発(development)    106
165                       データサイエンス(data science), 統計分析    103
166            AI・機械学習, ソーシャルメディアマーケティング, ビッグデータ, 機械学習    103
167                                          コミュニケーション    100
168                                      AI・機械学習, 統計分析     99
169       UX（ユーザー体験）デザイン, デザインとイラストレーションのツール, デザイン_創造力     96
170                              世界の言語, 語学学習(language)     95
171                     データサイエンス(data science), ビッグデータ     94
172                                   デザイン_創造力, 芸術・創造性     93
173                                            プロマネツール     89
174                    AI・機械学習, ソーシャルメディアマーケティング, 機械学習     84
175        IT×ビジネス, データサイエンス(data science), 推奨講座, 機械学習     81
176  PMI Professional Development Units（PDU）, プロジェク...     78
177         おすすめ講座, 推奨講座, 語学学習(language), コミュニケーションの基本     77
178                                    DevOps, 生成AIツール     74
179                           ソフトウェアエンジニアリング, プロジェクト管理     73
180                                            生成AIツール     71
181                              AI・機械学習, ビッグデータ, 機械学習     70
182    おすすめ講座, 業務効率化_エクセル_プレゼン, オフィスの生産性向上とコラボレーションツール     68
183                  タレントマネジメント, 人材開発, 業務効率化_エクセル_プレゼン     65
184                                    AI・機械学習, ビッグデータ     62
185   コンテンツマーケティング, デジタルマーケティング, ビジネス向け生成AI, マーケティング戦略     61
186              NASBA継続的専門教育（CPE）, キャリア成功, ビジネス向け生成AI     61
187   PMI Professional Development Units（PDU）, プロマネツール     59
188                                         財務モデリング・分析     59
189                           IT×ビジネス, プログラミング言語, 機械学習     56
190                              スピーチとプレゼンテーション, 財務_会計     56
191                         デザインとイラストレーションのツール, 芸術・創造性     55
192                               DevOps, テクノロジー向け生成AI     52
193                                   企業会計, 財務モデリング・分析     52
194  3Dとアニメーションのツール, デザインとイラストレーションのツール, ハードウェア, デザ...     52
195                                ビジネス向け生成AI, リーダーシップ     46
196                                         サプライチェーン管理     45
197                               スピーチとプレゼンテーション, 英語学習     44
198                ダイバーシティ、エクイティ、インクルージョン（DEI）, ビジネス戦略     41
199                                    IT×ビジネス, ビジネス戦略     40
200                                       ファイナンス, 企業会計     40
201                                 ビジネス向け生成AI, 新規事業開発     35
202             ダイバーシティ、エクイティ、インクルージョン（DEI）, チームマネジメント     34
203                                           英語学習, 言語     33
204                                   IT資格, ビジネス向け生成AI     32
205                         ソフトウェアエンジニアリング, ビジネス向け生成AI     31
206                           コンテンツマーケティング, ビジネス向け生成AI     30
207                                 アナリティクス, プログラミング言語     30
208                    IT×ビジネス, オススメ講座, ソフトウェアエンジニアリング     27
209                             英語試験準備, 語学学習(language)     27
210                               クラウド資格, サイバーセキュリティ認証     26
211                              リーダーシップ, 海外注目ソフトスキル講座     26
212                                    アナリティクス, データ可視化     25
213                      サイバーセキュリティ認証, 開発(development)     24
214                            DBデザイン・開発, テクノロジー向け生成AI     24
215            アナリティクス, オフィスの生産性向上とコラボレーションツール, データ可視化     23
216                                 ビジネス向け生成AI, ビジネス戦略     20
217                               テクノロジー向け生成AI, モバイル開発     18
218                              ビジネス向け生成AI, マーケティング戦略     18
219              DBデザイン・開発, プログラミング言語, 開発(development)     18
220                  オフィスの生産性向上とコラボレーションツール, プレゼンテーション     17
221                          ビジネス向け生成AI, マーケティング分析と自動化     17
222           OS（オペレーティングシステム）, オフィスの生産性向上とコラボレーションツール     17
223                     デザインとイラストレーションのツール, ビジネス向け生成AI     17
224                                     おすすめ講座, ビジネス分析     16
225                                    ウェブ開発, デザイン_創造力     16
226                          IT×ビジネス, ウェブ開発, プログラミング言語     16
227                             ペイドメディア, マーケティング分析と自動化     15
228                         アジャイル・スクラム, キャリア成功, プロマネ資格     15
229                    ソフトウェアエンジニアリング, 開発(development)     15
230                         テクノロジー向け生成AI, ビッグデータ, 機械学習     14
231                         NASBA継続的専門教育（CPE）, リーダーシップ     14
232                           マーケティング分析と自動化, マーケティング戦略     14
233                                      チームマネジメント, 会計     13
234                          NASBA継続的専門教育（CPE）, ファイナンス     12
235                         コミュニケーションの基本, 海外注目ソフトスキル講座     12
236                         IT資格, クラウド資格, テクノロジー向け生成AI     11
237                                         タレントマネジメント     11
238                                  DevOps, ソフトウェアテスト     10
239             コミュニケーションの基本, ビジネス向け生成AI, 文章のコミニュケーション     10
240                              NASBA継続的専門教育（CPE）, 会計      9
241                                               推奨講座      9
242                         プレゼンテーション, 業務効率化_エクセル_プレゼン      9
243       3Dとアニメーションのツール, デザインとイラストレーションのツール, デザイン_創造力      9
244                      IT資格, クラウド資格, 開発(development)      9
245                                               労働安全      9
246                       ソフトウェアエンジニアリング, テクノロジー向け生成AI      9
247                                                 言語      8
248                                 ビジネス向け生成AI, ファイナンス      8
249                            ハードウェア, 開発(development)      8
250                           おすすめ講座, ビジネス分析, プロジェクト管理      8
251                                   ビジネス分析, プロジェクト管理      7
252                   Offensive Security, テクノロジー向け生成AI      7
253                                          プレゼンテーション      7
254                       コミュニケーションの基本, 語学学習(language)      7
255  PMI Professional Development Units（PDU）, アジャイル...      6
256                                 テクノロジー向け生成AI, 機械学習      6
257                          スプレッドシート, 業務効率化_エクセル_プレゼン      6
258                         デジタルマーケティング, マーケティング分析と自動化      6
259                 ダイバーシティ、エクイティ、インクルージョン（DEI）, 人事の基礎      6
260                      NASBA継続的専門教育（CPE）, 財務モデリング・分析      5
261                                  ビジネス向け生成AI, 個人の成長      5
262          CompTIA Continuing Education（CE）, OSとサーバー      5
263               ダイバーシティ、エクイティ、インクルージョン（DEI）, リーダーシップ      5
264                                 文章のコミニュケーション, 英語学習      4
265                            スピーチとプレゼンテーション, リーダーシップ      4
266                              リーダーシップ, 文章のコミニュケーション      4
267                 3Dとアニメーションのツール, デザインとイラストレーションのツール      4
268             CompTIA Continuing Education（CE）, IT資格      4
269                             スピーチとプレゼンテーション, 芸術・創造性      4
270                                     DevOps, ハードウェア      4
271                                  DBデザイン・開発, モバイル開発      3
272                              ウェブ開発, ソフトウェアエンジニアリング      3
273                             ネットワーク, 新規事業立案_マーケティング      3
274                                      ディフェンシブセキュリティ      3
275                                  投資・株式, 財務モデリング・分析      3
276                              IT資格, アナリティクス, データ可視化      3
277                                    アナリティクス, クラウド開発      3
278                               ビジネス向け生成AI, プロジェクト管理      3
279                       3Dとアニメーションのツール, コンテンツマーケティング      3
280                              IT資格, 開発(development)      3
281                           マーケティング分析と自動化, 検索エンジン最適化      3
282                              ビジネス向け生成AI, 検索エンジン最適化      2
283                              ビジネス向け生成AI, プレゼンテーション      2
284                      サイバーセキュリティ意識, 開発(development)      2
285                              機械学習, 開発(development)      2
286  NASBA継続的専門教育（CPE）, コミュニケーションの基本, ダイバーシティ、エクイティ...      2
287                             キャリア成功, メールと生産性, 人事の基礎      2
288                            ビジネス向け生成AI, プロダクトマネジメント      2
289                                      アナリティクス, 統計分析      2
290                        テクノロジー向け生成AI, ノーコード/ローコード開発      2
291                                       ビジネス戦略, 統計分析      1
292                                 IT資格, サイバーセキュリティ意識      1
293                          ノーコード/ローコード開発, ビジネス向け生成AI      1
294                                 DBデザイン・開発, アナリティクス      1
295                       ソーシャルメディアマーケティング, ビジネス向け生成AI      1
296                                         人材開発, 英語学習      1
297                      ソーシャルメディアマーケティング, デジタルマーケティング      1
298                    アナリティクス, オフィスの生産性向上とコラボレーションツール      1
299              NASBA継続的専門教育（CPE）, ビジネス向け生成AI, ビジネス戦略      1
300                                 テクノロジー向け生成AI, 運用管理      1
301                  3Dとアニメーションのツール, ゲームデザイン, デザイン_創造力      1
302                             3Dとアニメーションのツール, 芸術・創造性      1
303                                        ウェブ開発, 機械学習      1
304                                 ファイナンス, 財務モデリング・分析      1

# career

In [18]:
df_career.head()

,社員番号,自分の能力を発揮できる仕事上の得意分野が見つかっている\n,自分はどんな仕事をやりたいのか明らかである \n,自分は何を望んで今の仕事をしているのかわかっている\n,自分なりの職業的な生き方に関する目標・目的がはっきりしている\n,自分のこれからのキャリアには、あまり関心がない\n,これからのキャリアを、より充実したものにしたいと強く思う\n,キャリア設計（職業生活の設計）は、自分にとって重要な課題である\n,これからのキャリアをどう歩むべきか、あまり考えていない\n,納得いくキャリアを歩めるかどうかは、自分の責任だと思う\n,キャリア形成は、自分自身の責任である\n,納得いくキャリアを歩めない原因の大半は周囲の環境にある\n,キャリアは周りの環境によって決められていくものだと思う\n,新しい環境や状況にも、わりあい早くなじんで対応している,職場環境の変化に対して自分なりに考えて対応している,新しい職場に移ってもすぐに自分らしさを発揮している,職場の制度や仕事が変わってもすぐ対応している,自分の職種・業界分野における最新動向を常に情報収集している,仕事のために新しいことをいろいろ勉強している,社会・経済の動きや成り行きに関する情報を、積極的に収集している,新しい知識・技術を積極的に学ぶように努めている,新しい人間関係が構築できるように、社内外の活動に積極的に参加している,仕事と直接関係ない人とも積極的に交流するようにしている,新しいネットワークづくりに常に取り組んでいる,自分の満足感を高めるように、仕事のやり方を工夫している,常に自発的に仕事を行っている,自分の価値観やポリシーを持って仕事に取り組んでいる,仕事の進め方や企画を立てる上で、今までの延長上のやり方ではなく、自分なりの発想を持って取り組んでいる,少人数チームで協力してタスクを完遂できる,メンバー全員のアイデアを取り入れて成果物を作れる,同僚や上司に向けて口頭でプレゼンテーションができる,スライドや動画などのデジタル資料を用いて情報を共有できる,異なる視点を比較して最適な解決策を選べる,正解が一つでない問題に対して解決策を導き出せる,複数のアイデアを試行し改善を重ねられる,困難な業務課題に対して独自の解決策を考案できる,自分の進捗をモニタリングし計画を柔軟に調整できる,フィードバックを受けて自ら仕事を改善できる,業務データを可視化し BI ダッシュボードで意思決定に活用できる,RPA／ノーコードツールで反復的な業務フローを自動化できる,生成 AI や機械学習モデルを業務改善に活用できる,クラウド環境のアクセス権限を監査し情報保護を徹底できる,デジタルマーケティング施策（SNS 広告等）をデータで最適化できる,顧客・市場データを用いて新商品・サービス企画を立案できる,クラウド／DevOps 環境を構築し IaC で継続的デプロイを管理できる,デジタルツインや IoT データを用いたサプライチェーン最適化を提案・実装できる
0,-4taxxVbT1nU-J5fHWmDfQ==,4 そう思う／当てはまる,3 どちらとも言えない,4 そう思う／当てはまる,3 どちらとも言えない,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,3 どちらとも言えない,4 そう思う／当てはまる,3 どちらとも言えない,3 どちらとも言えない,5 強くそう思う／とても当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,3 どちらとも言えない,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,4 そう思う／当てはまる,3 どちらとも言えない,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,4 そう思う／当てはまる,3 どちらとも言えない,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,5 強くそう思う／とても当てはまる,3 どちらとも言えない,2 あまりそう思わない／あまり当てはまらない,3 どちらとも言えない,3 どちらとも言えない,2 あまりそう思わない／あまり当てはまらない,2 あまりそう思わない／あまり当てはまらない,2 あまりそう思わない／あまり当てはまらない,2 あまりそう思わない／あまり当てはまらない
1,-EtuCRccKFQgi3UfXRvRkA==,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,1 全くそう思わない／全く当てはまらない,1 全くそう思わない／全く当てはまらない,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,1 全くそう思わない／全く当てはまらない,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,1 全くそう思わない／全く当てはまらない,1 全くそう思わない／全く当てはまらない,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,1 全くそう思わない／全く当てはまらない,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,1 全くそう思わない／全く当てはまらない
2,-JxDfe1I3lMhJDvo7mmvoA==,4 そう思う／当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,4 そう思う／当てはまる,1 全くそう思わない／全く当てはまらない,5 強くそう思う／とても当てはまる,4 そう思う／当てはまる,1 全くそう思わない／全く当てはまらない,4 そう思う／当てはまる,4 そう思う／当てはまる,1 全くそう思わない／全く当てはまらない,1 全くそう思わない／全く当てはまらない,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,2 あまりそう思わない／あまり当てはまらない,2 あまりそう思わない／あまり当てはまらない,4 そう思う／当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,3 どちらとも言えない,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,5 強くそう思う／とても当てはまる,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,2 あまりそう思わない／あまり当てはまらない
3,-Q5JF_Zj03QFrpbCJWPR3A==,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,4 そう思う／当てはまる,1 全くそう思わない／全く当てはまらない,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,1 全くそう思わない／全く当てはまらない,1 全くそう思わない／全く当てはまらない,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,4 そう思う／当てはまる,5 強くそう思う／とても当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,5 強くそう思う／とても当てはまる,4 そう思う／当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,2 あまりそう思わない／あまり当てはまらない,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,2 あまりそう思わない／あまり当てはまらない,3 どちらとも言えない,5 強くそう思う／とても当てはまる,3 どちらとも言えない,2 あまりそう思わない／あまり当てはまらない
4,-WNGlH_XHI3_niAnslX8gg==,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,3 どちらとも言えない,3 どちらとも言えない,2 あまりそう思わない／あまり当てはまらない,4 そう思う／当てはまる,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,5 強くそう思う／とても当てはまる,5 強くそう思う／とても当てはまる,1 全くそう思わない／全く当てはまらない,2 あまりそう思わない／あまり当てはまらない,3 どちらとも言えない,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,3 どちらとも言えない,2 あまりそう思わない／あまり当てはまらない,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない,2 あまりそう思わない／あまり当てはまらない,3 どちらとも言えない,2 あまりそう思わない／あまり当てはまらない,2 あまりそう思わない／あまり当てはまらない,4 そう思う／当てはまる,4 そう思う／当てはまる,2 あまりそう思わない／あまり当てはまらない

# dx

In [19]:
df_dx

,社員番号,研修実施日,研修カテゴリ,研修名
0,-2Sq3E0WkZj8pL7jxdL3Cg==,2024-04-15 00:00:00,リテラシー_DX基礎,【DX基礎研修】DX概論
1,-2Sq3E0WkZj8pL7jxdL3Cg==,2024-04-16 00:00:00,リテラシー_DX基礎,【DX基礎研修】ものづくり概論
2,-5W_JQCSTAYe2gGJMuT4_w==,2023-04-20 00:00:00,リテラシー_DX基礎,【DX基礎研修】社内事例①
3,-5W_JQCSTAYe2gGJMuT4_w==,2023-04-20 00:00:00,リテラシー_DX基礎,【DX基礎研修】社内事例②
4,-5W_JQCSTAYe2gGJMuT4_w==,2024-04-15 00:00:00,リテラシー_DX基礎,【DX基礎研修】イントロダクション
...,...,...,...,...
7095,zuplFpzBoM4c1dFy5HPXqg==,2024-10-04 00:00:00,データ利活用_実践,【DP13】テキストマイニングPython20241004
7096,zuplFpzBoM4c1dFy5HPXqg==,2024-10-23 00:00:00,データ利活用_実践,【DP07】モダンExcel PowerBI1023
7097,zxPKKLM85QljzRfp0yisow==,2023-08-23 00:00:00,データ利活用_実践,事業データと活用研修
7098,zxY0Eflwm1tYj1Wt6vo_1g==,2023-09-28 00:00:00,DX講演会,先生DX講演会
7099,zxY0Eflwm1tYj1Wt6vo_1g==,2024-11-29 00:00:00,DX講演会,【LB00-02】DX講演会 教育に生成AI 1129

In [20]:
df_dx['研修カテゴリ'].value_counts()

研修カテゴリ
リテラシー_DX基礎        4252
DX講演会             1301
データ利活用_実践          640
プロダクト開発_基礎         342
デジタルマーケティング_基礎     316
データ利活用_基礎          149
データ                 35
プロダクト開発_実践          24
システム開発_実践           23
DX勉強会               18
Name: count, dtype: int64

In [21]:
df_dx['研修名'].value_counts()

研修名
【DX基礎研修】DX概論                           453
【DX基礎研修】イントロダクション                      430
コミュニケーション学 「ツッコミ講座」                    333
【DX基礎研修】デジタルマーケ事例① インフルエンサーマーケティング     306
【DX基礎研修】ディスラプター②                       249
【DX基礎研修】ディスラプター基礎                      219
【DX基礎研修】社内事例④                          218
【LB00-02】DX講演会 教育に生成AI 1129            213
先生DX講演会                                206
【DX基礎研修】ディスラプター事例                      201
「デジタル革命の先にある新しい社会」                     182
【DX基礎研修】ものづくり事例③                       176
【DX基礎研修】社内事例②                          170
【DX基礎研修】ものづくり事例①                       169
【DX基礎研修】ものづくり事例②                       168
【DX基礎研修】DIF基礎                          158
【DX基礎研修】コンプライアンス・セキュリティ                153
【DX基礎研修】ものづくり概論 UX概論 UIUX実践例・工夫例       150
【DX基礎研修】社内事例①                          149
【DX基礎研修】社内事例③                          146
アフターデジタル時代のUX経営                        146
【DX基礎研修】デジタルマーケ事例② CDP                 137
【DX基礎研修】DIF事例① コアとなっている技術や思想とサービス紹介    131
IT３社講演会「生成AI」　                         127
【DX基礎研修】DIF事例②                         115
事業データと活用研修                             113
【DX基礎研修】ディスラプター①                       101
【LB00-1】講演会AI0925                       94
社内実例で学ぶセグメント＆スコアリング基礎                   80
【DX基礎研修】社内事例⑥                           80
UGC×SNSを活用したマーケティング研修〈12月）              77
動画×SNSを活用したマーケティング研修                    66
データと活用研修                                63
テキストマイニング演習                             53
【DX基礎研修】デジタルマーケ概論                       47
UX基礎                                    47
【DP05】効果検証研修                            45
インサイトフル導入研修                             39
基本【Power BIでラクラク可視化】データ分析入門             38
概要【Power BIでラクラク可視化】データ分析入門             38
データ連携を知る                                37
効果検証実践                                  37
【ゼロから始めるAI開発】社内外のAI活用事例                 36
応用【Power BIでラクラク可視化】データ分析入門             34
【DX基礎研修】DIF事例                           32
【DX基礎研修】デジタルマーケ事例①                      29
【DX基礎研修】ものづくり概論                         28
【DP15】プロンプトエンジニアリング研修20240905           27
【MB03】SNSマーケティング基礎①                     25
【DP04】アプローチのためのデータ利活用研修                 25
【MB04-1】 インサイトフル導入                      24
UI基礎②                                   23
【DP14】Python環境構築実践研修0911                23
過去事例から学ぶ開発トラブル予防                        23
【DX基礎研修】法人設立（データ）                       22
【DB07】統計基礎研修　                           21
Webサイト基礎　～はじめてのWebサイト～                  21
UI基礎                                    21
【PB04】UX基礎①                             20
【DB06】顧客データ管理・活用0920                    20
【DP13】テキストマイニングPython20241004           19
【MB02】デジマ基礎①                            19
【LB00-03】DX勉強会 1209                     18
UX基礎②                                   18
エリアマーケティングを考える                          18
【DP11】データ活用研修（中級編）                      18
【PB03】UI基礎①                             18
UI基礎〈8月）                                16
デジタルマーケティング基礎研修                         16
Webサイト基礎　～はじめてのWebサイト～〈8月）              16
アプリ開発基礎　～はじめてのWeb開発～                    16
アプリ開発基礎①                                15
知り得！データ利活用実践                            15
【DX基礎研修】デジタルマーケ事例②                      15
デザインスプリント実践                             14
【DP07】モダンExcel PowerBI1023              14
Webサイト基礎②                               14
【DP16】データサイエンティスト解説AI開発1004             14
 UI基礎                                   14
0802,0808【PB03】　UI基礎②　                  12
Webサイト基礎①                               12
アプリ開発基礎　～はじめてのWeb開発～〈8月）                12
デジタル初心者に向けたUI/UX＆Webデザイン研修              12
ログ定義基礎〈10月）                             11
インサイトフル導入Ⅱ                              11
デザインスプリント実践(10月4・11日）                   10
UX基礎〈8月）                                10
0830,0905【PB04】UX基礎②                    10
0806-07【PB05】Webサイト基礎①　                  9
デジタルマーケティング基礎                            9
0823,0829【MB02】デジタルマーケティング基礎②            9
【LP04-1】AI UnivプロンプトE初級1009,16           9
【MP07】プロンプトエンジニアリング中級                    8
0903,0904【PB05】Webサイト基礎②                 8
【LP04-2】AI UnivプロンプトE中級1113,19           8
【MB03】SNSマーケティング基礎②0913,0919             7
アプリ開発基礎②                                 5
0827-28【PB06】アプリ開発基礎①　                   3
【MB04-02】インサイト分析ワーク                      2
【PB06】アプリ開発基礎②911,0912                   2
Name: count, dtype: int64

# hr

In [22]:
df_hr

                          社員番号          カテゴリ       研修名                    実施日
0     -4taxxVbT1nU-J5fHWmDfQ==      3等級昇格者研修  3等級昇格者研修    2023-06-02 00:00:00
1     -4taxxVbT1nU-J5fHWmDfQ==  ビジネススキルアップ研修   マーケティング  2022/11/15,2022/11/29
2     -4taxxVbT1nU-J5fHWmDfQ==  ビジネススキルアップ研修   マーケティング  2022/11/15,2022/11/29
3     -4taxxVbT1nU-J5fHWmDfQ==  ビジネススキルアップ研修   マーケティング  2022/11/15,2022/11/29
4     -4taxxVbT1nU-J5fHWmDfQ==  ビジネススキルアップ研修   マーケティング  2022/11/15,2022/11/29
...                        ...           ...       ...                    ...
7071  zxmtr2h4ypvsNq02K9AMJg==  ビジネススキルアップ研修      管理会計  2023/10/23,2023/11/13
7072  zxmtr2h4ypvsNq02K9AMJg==  ビジネススキルアップ研修      管理会計  2023/10/23,2023/11/13
7073  zxmtr2h4ypvsNq02K9AMJg==  ビジネススキルアップ研修      管理会計  2023/10/23,2023/11/13
7074  zxmtr2h4ypvsNq02K9AMJg==  ビジネススキルアップ研修      管理会計  2023/10/23,2023/11/13
7075  zxmtr2h4ypvsNq02K9AMJg==  ビジネススキルアップ研修      管理会計  2023/10/23,2023/11/13

[7076 rows x 4 columns]

In [23]:
df_hr[df_hr['実施日']=='2024/5/17,2024/7/83']

                        社員番号      カテゴリ     研修名                  実施日
25  -WNGlH_XHI3_niAnslX8gg==  マネジメント研修  新任課長研修  2024/5/17,2024/7/83
26  -WNGlH_XHI3_niAnslX8gg==  マネジメント研修  新任課長研修  2024/5/17,2024/7/83

In [24]:
df_hr[df_hr['社員番号']=='zxmtr2h4ypvsNq02K9AMJg==']

                          社員番号          カテゴリ   研修名                    実施日
7070  zxmtr2h4ypvsNq02K9AMJg==  ビジネススキルアップ研修  管理会計  2023/10/23,2023/11/13
7071  zxmtr2h4ypvsNq02K9AMJg==  ビジネススキルアップ研修  管理会計  2023/10/23,2023/11/13
7072  zxmtr2h4ypvsNq02K9AMJg==  ビジネススキルアップ研修  管理会計  2023/10/23,2023/11/13
7073  zxmtr2h4ypvsNq02K9AMJg==  ビジネススキルアップ研修  管理会計  2023/10/23,2023/11/13
7074  zxmtr2h4ypvsNq02K9AMJg==  ビジネススキルアップ研修  管理会計  2023/10/23,2023/11/13
7075  zxmtr2h4ypvsNq02K9AMJg==  ビジネススキルアップ研修  管理会計  2023/10/23,2023/11/13

In [25]:
df_hr['実施日'].value_counts()

実施日
2024-12-01 00:00:00    316
2024-06-06 00:00:00    306
2023-07-07 00:00:00    252
2023-09-08 00:00:00    250
2023/7/10,2023/7/31    216
                      ...
2024-07-02 00:00:00      1
2024-04-12 00:00:00      1
2022-10-05 00:00:00      1
2022-12-06 00:00:00      1
2022-11-05 00:00:00      1
Name: count, Length: 767, dtype: int64

# overtime_work_by_month

In [ ]:
df_overtime_work_by_month

                            社員番号        date  hours
0       -1sqs0GXzpPJuAVKHUUFgg==  2022-01-01   10.0
1       -1sqs0GXzpPJuAVKHUUFgg==  2022-02-01   11.0
2       -1sqs0GXzpPJuAVKHUUFgg==  2022-03-01   18.0
3       -1sqs0GXzpPJuAVKHUUFgg==  2022-04-01   30.0
4       -1sqs0GXzpPJuAVKHUUFgg==  2022-05-01   27.0
...                          ...         ...    ...
101434  zxmtr2h4ypvsNq02K9AMJg==  2024-08-01   34.0
101435  zxmtr2h4ypvsNq02K9AMJg==  2024-09-01   34.0
101436  zxmtr2h4ypvsNq02K9AMJg==  2024-10-01   33.0
101437  zxmtr2h4ypvsNq02K9AMJg==  2024-11-01   26.0
101438  zxmtr2h4ypvsNq02K9AMJg==  2024-12-01   33.0

[101439 rows x 3 columns]

# position_history

In [27]:
df_position_history

                          社員番号  year 勤務区分        役職
0     -1sqs0GXzpPJuAVKHUUFgg==    22  正社員        一般
1     -1sqs0GXzpPJuAVKHUUFgg==    23  正社員        一般
2     -1sqs0GXzpPJuAVKHUUFgg==    24  正社員  グループリーダー
3     -2Sq3E0WkZj8pL7jxdL3Cg==    23  正社員        一般
4     -2Sq3E0WkZj8pL7jxdL3Cg==    24  正社員        一般
...                        ...   ...  ...       ...
8591  zxY0Eflwm1tYj1Wt6vo_1g==    23  正社員        一般
8592  zxY0Eflwm1tYj1Wt6vo_1g==    24  正社員        一般
8593  zxmtr2h4ypvsNq02K9AMJg==    22  正社員        一般
8594  zxmtr2h4ypvsNq02K9AMJg==    23  正社員        一般
8595  zxmtr2h4ypvsNq02K9AMJg==    24  正社員        一般

[8596 rows x 4 columns]

In [31]:
df_position_history.dtypes

社員番号    object
year     int64
勤務区分    object
役職      object
dtype: object

In [29]:
df_position_history['勤務区分'].value_counts()

勤務区分
正社員         7251
正社員(管理職)    1345
Name: count, dtype: int64

In [30]:
df_position_history['役職'].value_counts()

役職
一般          6653
グループリーダー     897
課長           686
部長           181
副部長           66
副本部長          34
室長            32
本部長           29
支社長           13
副室長            5
Name: count, dtype: int64

# 前処理済データの読み込み

In [5]:
df_prep_station = pd.read_pickle(os.path.join(DIR_INTERIM, "df_prep_station.pkl"))
df_prep_status = pd.read_pickle(os.path.join(DIR_INTERIM, "df_prep_status.pkl"))
df_prep_trip = pd.read_pickle(os.path.join(DIR_INTERIM, "df_prep_trip.pkl"))
df_prep_weather = pd.read_pickle(os.path.join(DIR_INTERIM, "df_prep_weather.pkl"))